### ISSUE TITLE
Non functional if there is no AMS connected to the printer. 

### ISSUE THREAD

**Issue by EdwardChamberlain** [synman/bambu-printer-manager#2]
Looks like this will only correctly receive updates from the printer if an AMS is connected. 

Minimum code to reproduce on my P1S (no AMS):

```py
from bpm.bambuconfig import BambuConfig
from bpm.bambuprinter import BambuPrinter
from bpm.bambutools import PrinterState
from bpm.bambutools import parseStage
from bpm.bambutools import parseFan


config = BambuConfig(hostname="192.168.1.51", access_code="36130849", serial_number="01P00A382200259")
printer = BambuPrinter(config=config)

printer.start_session()

while True:
    ...
```

error:
```
ERROR: an internal exception occurred
Traceback (most recent call last):
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/bpm/bambuprinter.py", line 93, in loop_forever
    printer.client.loop_forever(retry_first_connection=True)
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
         ^^^^^^^^^^^^^^^^
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
         ^^^^^^^^^^^^^^^^^^^
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
         ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/bpm/bambuprinter.py", line 90, in on_message
    self._on_message(json.loads(msg.payload.decode("utf-8")))
  File "/Users/edward/Documents/Github/BambuPy/env/lib/python3.12/site-packages/bpm/bambuprinter.py", line 270, in _on_message
    ams = (status["ams"]["ams"])[0]
          ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

errant line seems to be `bambuprinter.py::268`:
`"ams" in status and "ams" in status["ams"]` returns True on my machine (despite no AMS)

**Comment by synman** [comment]
I'll pull my ams tonight and get this working with just the external feed.

I thought I had it covered as I use the external feed with the AMS connected.

I must've missed something silly.

**Comment by synman** [comment]
My guess is the AMS node is there but its list (array) is empty.

This should be a very easy fix.  I just assumed if the AMS node was there, it would have a collection underneath it since it is already defined by an `ams` parent.

**Comment by synman** [comment]
Adding some notes here for posterity.

No AMS:
```
{
    "print": {
        "ams": {
            "ams": [],
            "ams_exist_bits": "0",
            "insert_flag": true,
            "power_on_flag": false,
            "tray_exist_bits": "0",
            "tray_is_bbl_bits": "0",
            "tray_now": "255",
            "tray_pre": "255",
            "tray_read_done_bits": "0",
            "tray_reading_bits": "0",
            "tray_tar": "255",
            "version": 1
        },
        "ams_rfid_status": 0,
        "ams_status": 0,
        "bed_target_temper": 0,
        "bed_temper": 17.5625,
        "big_fan1_speed": "0",
        "big_fan2_speed": "0",
        "chamber_temper": 5,
        "command": "push_status",
        "cooling_fan_speed": "0",
        "fan_gear": 0,
        "force_upgrade": false,
        "gcode_file": "",
        "gcode_file_prepare_percent": "0",
        "gcode_state": "IDLE",
        "heatbreak_fan_speed": "0",
        "hms": [],
        "home_flag": 3818896,
        "hw_switch_state": 0,
        "ipcam": {
            "ipcam_dev": "1",
            "ipcam_record": "disable",
            "mode_bits": 3,
            "resolution": "1920x1080",
            "timelapse": "disable"
        },
        "layer_num": 0,
        "lifecycle": "product",
        "lights_report": [
            {
                "mode": "on",
                "node": "chamber_light"
            }
        ],
        "mc_percent": 0,
        "mc_print_line_number": "0",
        "mc_print_stage": "1",
        "mc_print_sub_stage": 0,
        "mc_remaining_time": 0,
        "mess_production_state": "active",
        "msg": 0,
        "nozzle_target_temper": 0,
        "nozzle_temper": 17.78125,
        "online": {
            "ahb": false,
            "rfid": false,
            "version": 744270892
        },
        "print_error": 0,
        "print_type": "idle",
        "profile_id": "0",
        "project_id": "0",
        "queue_est": 0,
        "queue_number": 0,
        "queue_sts": 0,
        "queue_total": 0,
        "s_obj": [],
        "sdcard": true,
        "sequence_id": "2",
        "spd_lvl": 2,
        "spd_mag": 100,
        "stg": [],
        "stg_cur": 0,
        "subtask_id": "0",
        "subtask_name": "",
        "task_id": "0",
        "total_layer_num": 0,
        "upgrade_state": {
            "consistency_request": false,
            "cur_state_code": 0,
            "dis_state": 0,
            "err_code": 0,
            "force_upgrade": false,
            "message": "0%, 0B/s",
            "module": "",
            "new_ver_list": [],
            "new_version_state": 0,
            "progress": "",
            "sequence_id": 0,
            "status": ""
        },
        "upload": {
            "message": "",
            "progress": 0,
            "status": "idle"
        },
        "vt_tray": {
            "bed_temp": "0",
            "bed_temp_type": "0",
            "id": "254",
            "k": 0,
            "n": 1,
            "nozzle_temp_max": "270",
            "nozzle_temp_min": "240",
            "remain": 0,
            "tag_uid": "0000000000000000",
            "tray_color": "FFFFFFFF",
            "tray_diameter": "0.00",
            "tray_id_name": "",
            "tray_info_idx": "GFG98",
            "tray_sub_brands": "",
            "tray_temp": "0",
            "tray_time": "0",
            "tray_type": "PETG-CF",
            "tray_uuid": "00000000000000000000000000000000",
            "tray_weight": "0",
            "xcam_info": "000000000000000000000000"
        },
        "wifi_signal": "-44dBm",
        "xcam": {
            "halt_print_sensitivity": "medium",
            "printing_monitor": false
        }
    }
}
```

**Comment by synman** [comment]
looks like it is safe to rely on
```
"ams_exist_bits": "1"
```

**Comment by synman** [comment]
```
pip install bambu-printer-manager --upgrade 
```
should do the trick.  let me know if you run into any other issues and thank you for the bug report!

**Comment by EdwardChamberlain** [comment]
Can confirm this is now working! Thanks.
